- name: Master Playbook
  hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: Update repos
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

  tasks:
    - name: Execute all tasks
      block:
        - name: Install initial packages
          ansible.builtin.include_tasks: tasks/initial_packages.yml
        - name: Create users michel and ansible
          ansible.builtin.include_tasks: tasks/create_users.yml
        - name: Install ansible cron task
          ansible.builtin.include_tasks: tasks/cron.yml
        - name: Install bashrc and bash_aliases
          ansible.builtin.include_tasks: tasks/bash_configs.yml
        - name: Mount Share
          ansible.builtin.include_tasks: tasks/mount_share.yml
        - name: Setup Postfix
          ansible.builtin.include_tasks: tasks/postfix_setup.yml
        - name: Setup Unattended Upgrades
          ansible.builtin.include_tasks: tasks/unattended_upgrades.yml
        - name: Deploy Glances
          ansible.builtin.include_tasks: tasks/deploy_glances.yml
        - name: Deploy Docker
          ansible.builtin.include_tasks: tasks/deploy_docker.yml
        - name: Deploy NetData
          ansible.builtin.include_tasks: tasks/netdata_deploy.yml
        - name: Deploy Tailscale
          ansible.builtin.include_tasks: tasks/deploy_tailscale.yml
      ignore_errors: yes
      rescue:
        - name: Notify
          ansible.builtin.debug:
            msg: "Something went wrong, please check the logs"

  handlers:
    - name: Restart SSHD
      ansible.builtin.service:
        name: ssh
        state: restarted
