- name: Master Playbook
  hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: update repos
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
  
  tasks:
    - ansible.builtin.include_tasks: tasks/initial_packages.yml
    - ansible.builtin.include_tasks: tasks/create_users.yml
    - ansible.builtin.include_tasks: tasks/cron.yml
    - ansible.builtin.include_tasks: tasks/bash_configs.yml
    - ansible.builtin.include_tasks: tasks/postfix_setup.yml
    - ansible.builtin.include_tasks: tasks/unattended_upgrades.yml
    - ansible.builtin.include_tasks: tasks/netdata_deploy.yml
   