- name: Master Playbook
  hosts: localhost
  connection: localhost
  become: true

  vars:
    task_list:
      - tasks/initial_packages.yml
      # - tasks/create_users.yml
      # - tasks/cron.yml
      # - tasks/bash_configs.yml
      # - tasks/mount_share.yml
      # - tasks/postfix_setup.yml
      # - tasks/unattended_upgrades.yml
      - tasks/deploy_tailscale.yml
      - tasks/deploy_glances.yml
      # - tasks/deploy_docker.yml
    failure_counter: 0

  pre_tasks:
    - name: Update repos
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

  tasks:
    - name: Notify testing branch
      ansible.builtin.debug:
        msg: "This is the testing branch"

    - name: Execute all tasks
      ansible.builtin.include_tasks: "{{ current_task }}"
      loop: "{{ task_list }}"
      loop_control:
        loop_var: current_task
      register: task_result
      ignore_errors: true

    - name: Output failure counter
      ansible.builtin.debug:
        msg: "Failure counter: {{ failure_counter }}"

    - name: Send Pushover notification
      ansible.builtin.uri:
        url: "https://api.pushover.net/1/messages.json"
        method: POST
        body_format: form-urlencoded
        body:
          token: "a3hptta2gtupjywpjfd6gvkay7zsgc"
          user: "u8opak5mxtzxkbrvf5f4sgo6uidwhz"
          title: "Ansible ran on {{ ansible_hostname }}"
          message: "Failure counter: {{ failure_counter }}"
          priority: "{{ '-1' if failure_counter = '0' else '1' }}"
        headers:
          Content-Type: "application/x-www-form-urlencoded"

  handlers:
    - name: Restart SSHD
      ansible.builtin.service:
        name: ssh
        state: restarted
