- name: Master Playbook
  hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: Update repos
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages

  tasks:
    - name: Install initial packages
      ansible.builtin.include_tasks: tasks/initial_packages.yml
    - name: Create users michel and ansible
      ansible.builtin.include_tasks: tasks/create_users.yml
    - name: Install ansible cron task
      ansible.builtin.include_tasks: tasks/cron.yml
    - name: Install bashrc and bash_aliases
      ansible.builtin.include_tasks: tasks/bash_configs.yml
    - name: Setup Postfix
      ansible.builtin.include_tasks: tasks/postfix_setup.yml
    - name: Setup Unattended Upgrades
      ansible.builtin.include_tasks: tasks/unattended_upgrades.yml
    - name: Deploy NetData
      ansible.builtin.include_tasks: tasks/netdata_deploy.yml
    - name: Deploy Tailscale
      ansible.builtin.include_tasks: tasks/deploy_tailscale.yml
