- hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: update repos
      apt:
        update_cache: true
      changed_when: False
  
  tasks:
    - include_tasks: tasks/initial_packages.yml
    - include_tasks: tasks/create_users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/bash_configs.yml
    - include_tasks: tasks/postfix_setup.yml
    - include_tasks: tasks/unattended_upgrades.yml
    - include_tasks: tasks/netdata_deploy.yml
    - import_playbook: playbooks/netdata_install.yml
    - import_playbook: playbooks/netdata_configure.yml
    - import_playbook: playbooks/netdat_claim.yml