- hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: update repos
      apt:
        update_cache: yes
      changed_when: False
  
  tasks:
    - include: tasks/create_users.yml
    - include: tasks/cron.yml
    - include: tasks/initial_packages.yml