- name: Master Playbook
  hosts: localhost
  connection: localhost
  become: true

  vars:
    task_list:
      - tasks/initial_packages.yml
      - tasks/create_users.yml
      - tasks/cron.yml
      - tasks/bash_configs.yml
      - tasks/mount_share.yml
      - tasks/postfix_setup.yml
      - tasks/unattended_upgrades.yml
      - tasks/deploy_tailscale.yml
      - tasks/deploy_glances.yml
      - tasks/deploy_docker.yml

  pre_tasks:
    - name: Install artis3n.tailscale role
      ansible.builtin.command:
        cmd: ansible-galaxy install artis3n.tailscale
      changed_when: false

    - name: Update repos
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

  tasks:
    - name: Notify testing branch
      ansible.builtin.debug:
        msg: "This is the testing branch"

    - name: Execute all tasks
      # ignore_errors: true # noqa: ignore-errors
      ansible.builtin.include_tasks: "{{ current_task }}"
      loop: "{{ task_list }}"
      loop_control:
        loop_var: current_task
  
  handlers:
    - name: Restart SSHD
      ansible.builtin.service:
        name: ssh
        state: restarted
