- name: Master Playbook
  hosts: localhost
  connection: localhost
  become: true

  vars:
    tasks_successful: 0
    tasks_failed: 0
    tasks_skipped: 0

  pre_tasks:
    - name: Update repos
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

  tasks:
    - name: Execute all tasks
      ignore_errors: true # noqa: ignore-errors
      block:
        - name: Install initial packages
          ansible.builtin.include_tasks: tasks/initial_packages.yml

        - name: Create users michel and ansible
          ansible.builtin.include_tasks: tasks/create_users.yml

        - name: Install ansible cron task
          ansible.builtin.include_tasks: tasks/cron.yml

        - name: Install bashrc and bash_aliases
          ansible.builtin.include_tasks: tasks/bash_configs.yml

        - name: Mount Share
          ansible.builtin.include_tasks: tasks/mount_share.yml

        - name: Setup Postfix
          ansible.builtin.include_tasks: tasks/postfix_setup.yml

        - name: Setup Unattended Upgrades
          ansible.builtin.include_tasks: tasks/unattended_upgrades.yml

        - name: Deploy Glances
          ansible.builtin.include_tasks: tasks/deploy_glances.yml

        - name: Deploy Docker
          ansible.builtin.include_tasks: tasks/deploy_docker.yml

        - name: Deploy NetData
          ansible.builtin.include_tasks: tasks/netdata_deploy.yml

        - name: Deploy Tailscale
          ansible.builtin.include_tasks: tasks/deploy_tailscale.yml

        - name: Nofity
          ansible.builtin.debug:
            msg: "Test notification"
      always:
        - name: Increment successful tasks count
          ansible.builtin.set_fact:
            tasks_successful: "{{ tasks_successful | int + 1 }}"
          when: ansible_failed_task is not defined
        - name: Increment failed tasks count
          ansible.builtin.set_fact:
            tasks_failed: "{{ tasks_failed | int + 1 }}"
          when: ansible_failed_task is defined
        - name: Increment skipped tasks count
          ansible.builtin.set_fact:
            tasks_skipped: "{{ tasks_skipped | int + 1 }}"
          when: ansible_skipped_tasks is defined

    - name: Send Pushover notification
      ansible.builtin.uri:
        url: https://api.pushover.net/1/messages.json
        method: POST
        body_format: form-urlencoded
        body:
          token: "a3hptta2gtupjywpjfd6gvkay7zsgc"
          user: "u8opak5mxtzxkbrvf5f4sgo6uidwhz"
          message: "Tasks successful: {{ tasks_successful }}, Tasks failed: {{ tasks_failed }}, Tasks skipped: {{ tasks_skipped }}"
          title: "Ansible Run on {{ ansible_hostname }}"
          priority: "-1"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      delegate_to: localhost
      tags: notification

  handlers:
    - name: Restart SSHD
      ansible.builtin.service:
        name: ssh
        state: restarted
