- name: Install Packages
  ansible.builtin.apt:
    name:
      - cron
  when: not "'cron' in ansible_facts.packages"
  
- name: Install cron job (ansible-pull)
  ansible.builtin.cron:
    user: ansible
    name: "ansible provision"
    hour: "*/6"
    job: "/usr/bin/ansible-pull -o -U https://github.com/MichelfrancisBustillos/ansible_pull.git > /dev/null"
