- name: Install Cron
  ansible.builtin.apt:
    name:
      - cron

- name: Install cron job (ansible-pull)
  ansible.builtin.cron:
    user: root
    name: "ansible provision"
    minute: "0"
    hour: "*/6"
    job: "/usr/bin/ansible-pull -o -U https://github.com/MichelfrancisBustillos/ansible_pull.git > /dev/null"
