- name: Deploy Docker
  block:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true
      become: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: true

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      become: true

    - name: Deploy Portainer Agent
      community.general.docker_container:
        name: portainer_agent
        image: portainer/agent:2.27.7
        ports:
          - "9001:9001"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/lib/docker/volumes:/var/lib/docker/volumes"
          - "/:/host"
        restart_policy: always
        state: started
      become: true

    - name: Deploy Watchtower
      community.docker.docker_container:
        name: watchtower
        image: containrrr/watchtower
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          WATCHTOWER_CLEANUP: "true"
          WATCHTOWER_INCLUDE_STOPPED: "true"

          WATCHTOWER_SCHEDULE: "0 0 20 * * 3"
          WATCHTOWER_NOTIFICATIONS: "shoutrrr"
          WATCHTOWER_NOTIFICATION_URL: "pushover://shoutrrr:az5i4kisnta2vxwb26ze4pku8b3sum@u8opak5mxtzxkbrvf5f4sgo6uidwhz"
          TZ: "America/Chicago"
        state: started
      become: true

  rescue:
    - name: Handle task failure
      ansible.builtin.debug:
        msg: "A task in the Docker deployment block failed"
    - name: Increment failure counter
      ansible.builtin.set_fact:
        failure_counter: "{{ failure_counter | default(0) | int + 1 }}"
