- name: Install Tailscale
  ansible.builtin.command: |
    curl -fsSL https://tailscale.com/install.sh | sh
    sudo tailscale up --authkey tskey-auth-kjWyuL5CNTRL-3MubpvbhsZSXeTWuwB2SZSECct7ddH6U4
    sudo tailscale set --ssh