- name: Deploy UFW
  block:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present
      become: true

    - name: Set default Incoming Policy
      community.general.ufw:
        state: enabled
        direction: incoming
        policy: deny
      become: true

    - name: Set default Outgoing Policy
      community.general.ufw:
        state: enabled
        direction: outgoing
        policy: allow
      become: true

    - name: Allow SSH connections
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp
        source: '{{ item }}'
      loop:
        - 192.168.99.0/24
        - 192.168.1.0/24
      become: true

    - name: Allow Ping
      community.general.ufw:
        rule: allow
        proto: icmp
      become: true