- name: Deploy Docker
  block:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true
      become: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: true

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      become: true

    - name: Deploy Portainer Agent
      community.general.docker_container:
        name: portainer_agent
        image: portainer/agent:2.27.1
        ports:
          - "9001:9001"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/lib/docker/volumes:/var/lib/docker/volumes"
          - "/:/host"
        restart_policy: always
        state: started
      become: true

    - name: Deploy Watchtower
      vars:
        email_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31306636333934383630303137383439316361656364383432366463336664373836383561306337
          3032626431663366346565616665666264313338333834650a363065313564363536356562633232
          37333761316339356437613764343239333331363761333562643639383464663661336262383661
          3462313765623266300a656138386135343337626362306365343164613665333564386461653665
          63626563336266326365316430376661376337623835316632376265633265393764
      community.docker.docker_container:
        name: watchtower
        image: containrrr/watchtower
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          WATCHTOWER_CLEANUP: "true"
          WATCHTOWER_NOTIFICATION_EMAIL_FROM: "watchtower@katoteros.org"
          WATCHTOWER_NOTIFICATION_EMAIL_TO: "kotbe2hiax@pomail.net"
          WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "smtp.gmail.com"
          WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "587"
          WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "michelfrancisb@gmail.com"
          WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "{{ email_password }}" # noqa: jinja[invalid]
          WATCHTOWER_NOTIFICATIONS: "email"
          WATCHTOWER_NOTIFICATION_EMAIL_SUBJECT: "Watchtower Update Notification" 
        state: started
      become: true

  rescue:
    - name: Handle task failure
      ansible.builtin.debug:
        msg: "A task in the Docker deployment block failed"
    - name: Increment failure counter
      ansible.builtin.set_fact:
        failure_counter: "{{ failure_counter | default(0) | int + 1 }}"
