- name: Deploy UFW
  block:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present
      become: true

    - name: Set default in Policy
      community.general.ufw:
        state: enabled
        direction: incoming
        policy: deny
      become: true

    - name: Set default out Policy
      community.general.ufw:
        state: enabled
        direction: outgoing
        policy: allow
      become: true

    - name: Set defualt Routed Policy
      community.general.ufw:
        state: enabled
        direction: routed
        policy: deny
      become: true

    - name: Allow SSH connections
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp
        src: '{{ item }}'
      loop:
        - 192.168.99.0/24
        - 192.168.1.0/24
      become: true

    - name: Allow in on loopback
      community.general.ufw:
        rule: allow
        direction: in
        interface: lo
      become: true

    - name: Allow out on loopback
      community.general.ufw:
        rule: allow
        direction: out
        interface: lo
      become: true

    - name: Deny in from localhost
      community.general.ufw:
        rule: deny
        direction: in
        src: '{{ item }}'
      loop:
        - 127.0.0.0/8
        - ::1
      become: true

    - name: Enable UFW
      community.general.ufw:
        state: enabled
        logging: on
        

  rescue:
    - name: Handle failure
      ansible.builtin.debug:
        msg: "An error occurred during UFW deployment."
    - name: Increment failure counter
      ansible.builtin.set_fact:
        failure_counter: "{{ failure_counter | default(0) | int + 1 }}"