- name: Deploy Docker
  block:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true
      become: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: true

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      become: true

    - name: Get Docker Container Info
      docker_container_info:
        name: portainer

    - name: Check if Portainer agent is running
      ansible.builtin.command:
        cmd: docker ps --filter "name=portainer_agent" --format "{{ .Status }}"
      register: portainer_agent_status
      changed_when: false

    - name: Deploy Portainer Agent
      ansible.builtin.command:
        cmd: docker run -d -p 9001:9001 --name portainer_agent --restart=always \
             -v /var/run/docker.sock:/var/run/docker.sock \
             -v /var/lib/docker/volumes:/var/lib/docker/volumes \
             -v /:/host portainer/agent:2.27.1
      become: true
      when: portainer_agent_status.stdout == ""
      changed_when: false

    - name: Check if Watchtower is running
      ansible.builtin.command:
        cmd: docker ps --filter "name=watchtower" --format "{{ .Status }}"
      register: watchtower_status
      changed_when: false

    - name: Deploy Watchtower
      vars:
        email_key: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                64643231626239376133346130663762633863326432643839666461613732396239343535333263
                3235373665646663363065346535383139666532313263660a666630653633333236333637386332
                31616165613631663436653064383832356137656465636531353534376239666138613433653962
                3361396133326566660a383932346663626632373134313161353764343737643264386332303064
                65623966623364356365346634663234306236396266373535316266613462653537656431386537
                39333961636166666439633761303965333035653936316165643936366533336431623563303036
                373062303961393233396239313532373332
      ansible.builtin.command:
        cmd: docker run -d \
             --name watchtower \
             -v /var/run/docker.sock:/var/run/docker.sock \
             --cleanup \
             -e WATCHTOWER_NOTIFICATION_EMAIL_FROM="watchtower@katoteros.org" \
             -e WATCHTOWER_NOTIFICATION_EMAIL_TO="kotbe2hiax@pomail.net" \
             -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER="smtp.gmail.com" \
             -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT="587" \
             -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER="michelfrancisb@gmail.com" \
             -e WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD="{{ email_key }}" \
             -e WATCHTOWER_NOTIFICATIONS=email \
             containrrr/watchtower # noqa: jinja[invalid]
      become: true
      when: watchtower_status.stdout == ""
      changed_when: false

  rescue:
    - name: Handle task failure
      ansible.builtin.debug:
        msg: "A task in the Docker deployment block failed"
    - name: Increment failure counter
      ansible.builtin.set_fact:
        failure_counter: "{{ failure_counter | default(0) | int + 1 }}"
