- name: Download Tailscale Install Script
  ansible.builtin.get_url:
    url: https://tailscale.com/install.sh
    dest: /tmp/tailscale_install.sh
    mode: a=rwx
    force: true

- name: Install Tailscale
  ansible.builtin.command: bash /tmp/tailscale_install.sh
  register: result
  changed_when: "'0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.' not in result.stdout"

- name: Auth and Enable Tailscale
  ansible.builtin.command: sudo tailscale up --authkey tskey-auth-kd4Li3yVCC21CNTRL-GgEhLshnsuScyB8STz4dvS1u43mpQXXQ --ssh
  register: tailscale_result
  changed_when: tailscale_result.stdout != ""
