- name: Deploy Wazuh Agent
  block:
    - name: Add Wazuh repository GPG key
      ansible.builtin.apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present
      become: true

    - name: Add Wazuh repository
      ansible.builtin.apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        state: present
      become: true

    - name: Update apt and install Wazuh Agent
      ansible.builtin.apt:
        pkg: wazuh-agent
        state: present
        update_cache: true
      become: true

    - name: Configure Wazuh Agent
      ansible.builtin.lineinfile:
        dest: /var/ossec/etc/ossec.conf
        regexp: '<address>.*</address>'
        line: "<address>wazuh.katoteros.org</address>"
        state: present
        backup: true

    - name: Start and enable Wazuh Agent service
      systemd:
        name: wazuh-agent
        state: started
        enabled: true
        daemon_reload: true
  when: "'wazuh-manager.service' not in services"

  rescue:
    - name: Handle failure
      ansible.builtin.debug:
        msg: "An error occurred during Wazuh Agent deployment."
    - name: Increment failure counter
      ansible.builtin.set_fact:
        failure_counter: "{{ failure_counter | default(0) | int + 1 }}"