- name: Deploy Docker
  block:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true
      become: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: true

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      become: true

    - name: Create systemd override directory
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: "0755"

    - name: Docker Depends on Ark Mounting
      ansible.builtin.copy:
        content: |
          [Unit]
          After=mnt-Ark.mount
          Requires=mnt-Ark.mount
        dest: /etc/systemd/system/docker.service.d/override.conf
        mode: "0644"
      when: "'/mnt/Ark' in ansible_mounts | map(attribute='mount') | list"
      notify: Reload systemd & Restart Docker
      become: true

    - name: Configure Docker Logging
      ansible.builtin.copy:
        content: |
          {
            "log-driver": "syslog",
            "log-opts": {
              "syslog-address": "tcp://greylog.katoteros.org:518",
              "syslog-format": "rfc5424"
              "tag": "{{.ImageName}}/{{.Name}}/{{.ID}}"
            }
          }
        dest: /etc/docker/daemon.json
        mode: "0644"
      notify: Reload systemd & Restart Docker
      become: true

    - name: Deploy Watchtower
      vars:
        pushover_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63663436636461633361633636353932656231653233633066333930616533633162356463643931
          6632373736393938636535623930383861353935343338300a653463633062333731383837363838
          32323062306236643362613236656131353061386463396332376338373664643030386438316238
          3436343165646335630a356466383331343734343461656461623335323930363036376530613134
          62656339646637656264323964363161633365623533316636616365613330663033
        pushover_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65303162333732393164303563373532616538393666393335633631353334313061633934626365
          3834626564636565353938623532313763626661306230360a363663623163383862623363353139
          39396364643232663939373031323136383064323434343564656561393136626166393131396137
          3664656430336237660a373833643464626535383437383664613964663035396163373835343631
          33663739343564383966333065333063623630656366323739646234623561343564

      community.docker.docker_container:
        name: watchtower
        image: containrrr/watchtower
        restart_policy: unless-stopped
        recreate: true
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          WATCHTOWER_CLEANUP: "true"
          WATCHTOWER_INCLUDE_STOPPED: "true"

          WATCHTOWER_SCHEDULE: "0 0 20 * * 3"
          WATCHTOWER_NOTIFICATIONS: "shoutrrr"
          WATCHTOWER_NOTIFICATION_URL: "pushover://shoutrrr:{{ pushover_token }}@{{ pushover_user }}" # noqa: jinja[invalid]
          TZ: "America/Chicago"
        state: started
      become: true
      changed_when: false  # Prevents unnecessary changes on each run

  rescue:
    - name: Handle task failure
      ansible.builtin.debug:
        msg: "A task in the Docker deployment block failed"
    - name: Increment failure counter
      ansible.builtin.set_fact:
        failure_counter: "{{ failure_counter | default(0) | int + 1 }}"
