- name: Deploy IPTables
  block:
    - name: Allow incoming SSH from default VLAN
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 192.168.1.0/24
        jump: ACCEPT
        state: present

    - name: Allow incoming SSH from Management VLAN
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 192.168.99.0/24
        jump: ACCEPT
        state: present

    - name: Allow return traffic
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
        state: present

    - name: Allow ICMP (ping)
      ansible.builtin.iptables:
        chain: INPUT
        protocol: icmp
        jump: ACCEPT
        state: present

    - name: Drop all other incoming traffic
      ansible.builtin.iptables:
        chain: INPUT
        jump: DROP
        state: present