- name: Download NetData
  ansible.builtin.get_url:
    dest: /tmp/netdata-kickstart.sh 
    url: https://get.netdata.cloud/kickstart.sh
    mode: a=rwx
    changed_when: false

- name: Install NetData
  ansible.builtin.command:
    cmd: sh /tmp/netdata-kickstart.sh --nightly-channel --claim-token a3BIG_DKGw5w_MBpPWDmzrwH-UZQSOCuGvy1n5hkgxH2wR13As0Pzeux2DgHeNkRfhEvsjGDUOyh7gbgDA4bXdbf3Ksj8CRgfMIq3apT3HOFize5I50vO6jYz5SbbhLQCJ5y95c --claim-rooms ca2ddf95-7273-4233-b287-7f775b29178d --claim-url https://app.netdata.cloud
    changed when: false