- name: Deploy password policy
  block:
    - name: Install libpam-pwquality
      ansible.builtin.apt:
        name: libpam-pwquality
        state: present
        update_cache: yes

    - name: Configure /etc/security/pwquality.conf
      ansible.builtin.lineinfile: