- name: Deploy password policy
  block:
    - name: Install libpam-pwquality
      ansible.builtin.apt:
        name: libpam-pwquality
        state: present
        update_cache: yes

    - name: Configure pam_faillock
      ansible.builtin.copy:
        dest: /usr/share/pam-configs/faillock
        content: |
          Name: Enable pam_faillock to deny access
          Default: yes
          Priority: 0
          Auth-Type: Primary
          Auth: 
              [default=die]   pam_faillock.so authfail
        mode: '0755'
    
    - name: Configure pam_faillock_notify
      ansible.builtin.copy:
        dest: /usr/share/pam-configs/faillock_notify
        content: |
          Name: Notify of failed login attempts and reset count upon success
          Default: yes
          Priority: 1024
          Auth-Type: Primary
          Auth: requisite pam_faillock.so preauth
          Account-Type: Primary
          Account: required pam_faillock.so
        mode: '0755'

    - name: Configure pwfailed attempts
      ansible.builtin.lineinfile:
        path: /etc/security/faillock.conf
        line: "{{ item }}"
      loop:
        - "deny = 5"
        - "unlock_time = 900"
        - "even_deny_root"

    - name: Enable pam_modules
      ansible.builtin.command:
        cmd: "pam-auth-update --enable {{ item }}"
      loop:
        - faillock
        - faillock_notify
        - unix
        - pwquality
        - pwhistory

  rescue:
    - name: Handle task failure
      ansible.builtin.debug:
        msg: "A task in the PAM configuration block failed"
    - name: Increment failure counter
      ansible.builtin.set_fact:
        failure_counter: "{{ failure_counter | default(0) | int + 1 }}"