- name: Install Mail Packages
  ansible.builtin.apt:
    name:
      - libsasl2-modules
      - mailutils

- name: Copy sasl_passwd
  ansible.builtin.copy:
    src: files/sasl_passwd
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: u=rw,go=
    force: true

- name: Copy main.cf
  ansible.builtin.copy:
    src: files/main.cf
    dest: /etc/postfix/main.cf
    mode: u=rw,go=r
    force: true

- name: Hash sasl_passwd
  ansible.builtin.command: /usr/sbin/postmap hash:/etc/postfix/sasl_passwd
  changed_when: false

- name: Restart and Enable Postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: true
