- name: Copy sasl_passwd
  ansible.builtin.copy:
    src: files/sasl_passwd
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: rw-------

- name: Copy main.cf
  ansible.builtin.copy:
    src: files/main.cf
    dest: /etc/postfix/main.cf

- name: Hash sasl_passwd
  ansible.builtin.command:
    /usr/sbin/postmap hash:/etc/postfix/sasl_passwd

- name: Restart and Enable Postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: true
