- name: Copy unattended-upgrades config
  ansible.builtin.copy:
    src: files/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    force: True

- name: Copy auto-upgrades config
  ansible.builtin.copy:
    src: files/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: Dpkg reconfigure
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
  register: dpkg_reconfigure_unattended_upgrades

- name: Enable systemd service
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started
    enabled: yes
    daemon_reload: yes
    