- name: Copy unattended-upgrades config
  copy:
    src: files/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Copy auto-upgrades config
  copy:
    src: files/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: Dpkg reconfigure
      command:
        cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
      register: dpkg_reconfigure_unattended_upgrades
      when:
        - unattended_upgrades_config_set.changed or
          unattended_upgrades_settings_set.changed

- name: Enable systemd service
  systemd:
    name: unattended-upgrades
    state: started
    enabled: yes
    daemon_reload: yes