- name: Install Unattended-Upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
  when: not "'unattended-upgrades' in ansible_facts.packages"

- name: Copy unattended-upgrades config
  ansible.builtin.copy:
    src: files/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    force: true
    mode: u=rw,go=r

- name: Copy auto-upgrades config
  ansible.builtin.copy:
    src: files/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: u=rw,go=r

- name: Dpkg reconfigure
  ansible.builtin.command: dpkg-reconfigure -f noninteractive unattended-upgrades
  register: dpkg_reconfigure_unattended_upgrades
  changed_when: dpkg_reconfigure_unattended_upgrades != ""

- name: Enable systemd service
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started
    enabled: true
    daemon_reload: true
