- name: Configure unattended upgrades
  block:
    - name: Install Unattended-Upgrades
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present
        update_cache: true
      become: true
      notify: Count Changes

    - name: Copy unattended-upgrades config
      ansible.builtin.copy:
        src: files/50unattended-upgrades
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        force: true
        mode: '0644'
      become: true
      notify: Count Changes

    - name: Copy auto-upgrades config
      ansible.builtin.copy:
        src: files/20auto-upgrades
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        mode: '0644'
      become: true
      notify: Count Changes

    - name: Dpkg reconfigure
      ansible.builtin.command: dpkg-reconfigure -f noninteractive unattended-upgrades
      register: dpkg_reconfigure_unattended_upgrades
      changed_when: false
      become: true
      notify: Count Changes

    - name: Enable systemd service
      ansible.builtin.systemd:
        name: unattended-upgrades
        state: started
        enabled: true
        daemon_reload: true
      become: true
      notify: Count Changes
  rescue:
    - name: Handle task failure
      ansible.builtin.debug:
        msg: "A task in the unattended upgrades block failed"
    - name: Increment failure counter
      ansible.builtin.set_fact:
        failure_counter: "{{ failure_counter | default(0) | int + 1 }}"
