name: Ansible Test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs: 
  ansible-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.15
          testing-type: sanity
          pre-test-cmd: 'rm -rf .devcontainer/ .git* .pre-commit-config.yaml'
